apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: operator-kas-fleetshard-v8ht
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operator-kas-fleetshard-v8ht
    app.kubernetes.io/part-of: fleetshard
  name: operator-kas-fleetshard-v8ht
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: operator-kas-fleetshard-v8ht
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: operator-kas-fleetshard-v8ht
    spec:
      containers:
      - image: quay.io/scoheb/user-workload:NA_QT-operator-kas-fleetshard-v8ht
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
