apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: operator-kas-fleetshard-v8ht
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operator-kas-fleetshard-v8ht
    app.kubernetes.io/part-of: fleetshard
  name: operator-kas-fleetshard-v8ht
  namespace: user1-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: operator-kas-fleetshard-v8ht
    weight: null
status: {}
