apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: api-kas-fleetshard-qjmc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-kas-fleetshard-qjmc
    app.kubernetes.io/part-of: fleetshard
  name: api-kas-fleetshard-qjmc
  namespace: user1-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: api-kas-fleetshard-qjmc
    weight: null
status: {}
